### PR TITLE
Add support for unquoted multi-word font family names

### LINKED ISSUE #4: Fails to parse unquoted but valid font names with spaces
According to https://developer.mozilla.org/en-US/docs/Web/CSS/font-family 

"Font family names must either be given quoted as strings, or unquoted as a sequence of one or more identifiers. This means that punctuation characters and digits at the start of each token must be escaped in unquoted font family names."

Their "valid" example of this is: `font-family: Gill Sans Extrabold, sans-serif;`

hanamura/font-family fails to parse this, throwing an error.

Here is a test which should pass:
```
    it('should parse multi-word family names even if not quoted', function() {
      // According to https://developer.mozilla.org/en-US/docs/Web/CSS/font-family 
      // "Font family names must either be given quoted as strings, or unquoted as a sequence
      //  of one or more identifiers. This means that punctuation characters and digits at the
      //  start of each token must be escaped in unquoted font family names."
      // They give a valid example of this: "font-family: Gill Sans Extrabold, sans-serif;"
      var result = parse('Gill Sans Extrabold, sans-serif');

      expect(result).to.have.length(2);
      expect(result[0]).to.equal('Gill Sans Extrabold');
      expect(result[1]).to.equal('sans-serif');
    });
```

### PR DESCRIPTION
**Pull request by papandreou**
Fixes #4

### CODE REVIEW

**Comment by scottctr** [comment]
I'm having this same issue. Anything I can do to facilitate this merge?

**Comment by papandreou** [comment]
While we're waiting I've published a fork with this change: https://www.npmjs.com/package/font-family-papandreou

**Review by SmilinBrian — APPROVED** [review]
Thank you for this!

**Comment by papandreou** [comment]
@hanamura, anything I can do to help move this forward?

**Comment by papandreou** [comment]
Ping @hanamura?

**Comment by papandreou** [comment]
@hanamura, any chance you can take a look at this? :hugs:

**Pull request closed without merging**
